### PR TITLE
Add quiet parameter to MyPetExpEvent constructor.

### PR DESCRIPTION
**Pull request by rafaelflromao**

### CODE REVIEW

**Comment by Jakllp** [comment]
Why do you need this?

**Comment by rafaelflromao** [comment]
Because I need a way to listen when pet earns XP, currently when pet is activated event is called too.

**Comment by Jakllp** [comment]
Ah I see basically MyPet was always throwing the ExpEvent but would potentially not throw the LevelUp Event if it was quiet.

I will need to look at some more code. Will get back to you

**Comment by Jakllp** [comment]
I see - this seems to be mainly useful for external API-Calls but as you said also when the pet is activated which doesn't make any sense.

Approved, will be in the next build

You will also get a mention on our discord when that build drops.

Thank you ^^

**Pull request merged**
