### PR TITLE
Make petbehavior persistent

### PR DESCRIPTION
**Pull request by destro174**

### CODE REVIEW

**Comment by Jakllp** [comment]
Could you change the base branch to dev on your end (as it will be ugly as hell commit if we change it in here)?
Other than that this looks good

**Comment by Jakllp** [comment]
I know your branch ist called dev/... but it doesn't seem to be based on the MyPet-Dev branch.  
I would like to merge this into dev but it would be a very ugly commit if we change it in the PR.  
Can you change that?

In general your changes look good tho!

**Comment by destro174** [comment]
Done. Let me know if I should make any other changes.

**Comment by Jakllp** [comment]
Looks good ^^  
Thank you for the contribution!

**Pull request merged**
